Create Asset model
TheGnarCo/GEAR pull request #40
Opened 2022-07-21 22:53 UTC by stevemeisner

This PR:

- adds new `Asset` model
- associates Assets with Users
- creates an `asset_type` enum

```mermaid
erDiagram
  User ||--|{ Asset : has_many
  User {
  }
  Asset {
    id ID
    id user_id
    datetime created_at
    datetime updated_at
    string model_number
    string serial_number
    date approximate_purchase_date
    string mac_address
    string phone_number
    integer asset_type
    text description
  }
```

---

### Notes

- **MAC Address is optional** 
- **The optional description field**
  - The thought being that this would be "nice to have" in the event that an asset is of an "other" type. Does this make sense?
- **The `asset_type` enum**
  - What should go in this list?

2022-07-21 23:02 UTC, stevemeisner reviewed
@efertsch I just saw [your comments](https://github.com/TheGnarCo/GEAR/issues/20#issuecomment-1192003588), and that all makes sense to me!

The optional description field is tied to the "other" `asset_type` use case. And yes as you pointed out, `type` is indeed a reserved word 😅!

Your thoughts made sense on the "other" category not really being useful in this case. Should the `description` field and and "other" enum value go away? I'm thinking so at this point.

2022-07-22 15:18 UTC, alxjrvs requested changes
Other than the `user_id` validations and a minor comment on the factories, I think this looks A-OK.

2022-07-22 15:18 UTC, alxjrvs commented on spec/factories/assets.rb
> +    approximate_purchase_date { "2022-07-21" }
I think you want this to return a `date`, not a `string`. You can spin up a new `DAte` object from this pretty quickly with `Date.new(datestring)`, or you can look into the `Faker` gem for ways to get random data like this.

2022-07-22 15:18 UTC, alxjrvs commented on spec/models/asset_spec.rb
> +    it { should validate_presence_of(:user_id) }
Can be removed (redundant, see model)

2022-07-22 15:18 UTC, alxjrvs commented on spec/models/asset_spec.rb
> +  describe "associations" do
while normally I am a huge fan of extra descriptive describe blocks, I kinda feel like this file could just be the `it`s all lined up. 

This is the most minor of critiques, and is nearly just me rambling.

2022-07-22 17:03 UTC, jyurek commented on db/migrate/20220721201913_create_assets.rb
> +      t.integer :asset_type, null: false, default: 0
```suggestion
      t.string :asset_type, null: false, default: "laptop"
```

(Related to my above comment)

2022-07-22 17:03 UTC, jyurek commented on spec/models/asset_spec.rb
> +  describe "associations" do
I like sectioning off things like this. Though it is only one, so I see your point there. Takeaway, @stevemeisner : It's not set in stone. :)

2022-07-22 18:29 UTC, efertsch commented
> @efertsch I just saw [your comments](https://github.com/TheGnarCo/GEAR/issues/20#issuecomment-1192003588), and that all makes sense to me!
> 
> The optional description field is tied to the "other" `asset_type` use case. And yes as you pointed out, `type` is indeed a reserved word 😅!
> 
> Your thoughts made sense on how the "other" category isn't really being useful in this case. Should the `description` field and and "other" enum value go away? I'm thinking so at this point.

I am not 100% sure of the requirements but if I were building this on my own, I probably wouldn't include "other" if I was being intentional about cataloging 😄

2022-07-22 18:49 UTC, alxjrvs approved these changes

2022-07-22 18:50 UTC, merged